# Generated by Django 4.2.1 on 2023-05-06 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0002_rename_cliente_clientes_alter_creditos_monto_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos',
            name='tipo_Credito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_creditos.tipo_credito'),
            preserve_default=False,
        ),
    ]
