# Generated by Django 4.2.1 on 2023-05-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0003_creditos_tipo_credito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditos',
            old_name='tipo_Credito',
            new_name='tipo_credito',
        ),
    ]
