# Generated by Django 4.2.1 on 2023-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0004_rename_tipo_credito_creditos_tipo_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='monto_cuota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_credito',
            name='nombre_credito',
            field=models.CharField(max_length=256),
        ),
    ]
