# Generated by Django 4.2.1 on 2023-05-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0005_creditos_fecha_alter_creditos_monto_cuota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos',
            name='fecha_otorgamiento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
