# Generated by Django 4.2.1 on 2023-05-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0006_creditos_fecha_otorgamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos',
            name='cuotas_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
