# Generated by Django 4.2.1 on 2023-05-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0008_cuotas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditos',
            name='cuotas_info',
        ),
        migrations.DeleteModel(
            name='Cuotas',
        ),
    ]
