# Generated by Django 4.2.1 on 2023-05-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0011_clientes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='dni',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
